import FIREBASE_AUTH from './Auth';
import FIREBASE_DATABASE from './Database';
import FIREBASE_STORAGE from './Storage';
import PROVIDER from './Provider';
const CLIENT_ID = 'ZTCEMNLQLDSTSUJ3KUJVBWSG5UX1DGDFNJPOICB4ON3N4DXJ';
const CLIENT_SECRET = '31FAZ401G1DI3SX0JNK5ENBO43NS5PYE0Q0FM4OD4GYGIC0C';
export {FIREBASE_AUTH, FIREBASE_DATABASE, FIREBASE_STORAGE, PROVIDER, CLIENT_ID, CLIENT_SECRET};